language: c++
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages: [ninja]
  homebrew:
    packages: [ninja]
before_script:
  - mkdir build
  - cd build
  - cmake -GNinja ..
script:
  - ninja
  - ctest --output-on-failure
