language: c++
os:
  - linux
  - osx
dist: bionic
sudo: required
compiler:
  - clang
  - gcc
install:
  - ci/install_deps.sh
before_script:
  - mkdir build
  - cd build
  - cmake -GNinja ..
script:
  - ninja
  - ctest --output-on-failure
