/**
 * @file hrglib/feature_headers.hpp
 * @brief Autogenerated #include statements required for feature types.
 */
#pragma once
/*[[[cog
import cog
import yaml

with open(FEATURES_YAML) as f:
    features = yaml.load(f, Loader=yaml.SafeLoader)
    headers = ['<string>']
    for feat in features:
        header = feat.get('header', '<string>')
        if header not in headers:
             headers.append(header)
    for header in headers:
        cog.outl(f"#include {header}")
]]]*/
//[[[end]]]
