/**
 * @file hrglib/feature_list.hpp
 * @brief Definition of `HRGLIB_FEATURE_LIST()` macro.
 */
#pragma once

#ifndef HRGLIB_FEATURE_LIST
/**
 * @brief Second-order macro used as a canonical source for emitting all dependent feature lists,
 *     including the implementation of `hrglib::feature_name` enum.
 * @todo This list can be autogenerated from features.yaml or some other external database.
 */
#define HRGLIB_FEATURE_LIST(visitor) \
    /*[[[cog
import cog
import yaml

with open(FEATURES_YAML) as f:
    features = yaml.load(f, Loader=yaml.SafeLoader)
    for feat in features:
        cog.outl(f"visitor({feat['name']}, {feat.get('type', 'string')}, \"{feat['description']}\") \\")
    ]]]*/
    //[[[end]]]

#endif
