/**
 * @file hrglib/feature_list.hpp
 * @brief Definition of `HRGLIB_FEATURE_LIST()` macro.
 */
#pragma once

#ifndef HRGLIB_FEATURE_LIST
/**
 * @brief Second-order macro used as a canonical source for emitting all dependent feature lists,
 *     including the implementation of `hrglib::feature_name` enum.
 * @todo This list can be autogenerated from features.yaml or some other external database.
 */
#define HRGLIB_FEATURE_LIST(visitor) \
    visitor(name, string, "Name of the HRG node.") \
    visitor(punc, string, "Prepunctuation chars defined on tokens.") \
    visitor(prepunc, string, "") \
    visitor(whitespace, string, "") \
    visitor(start_pos, size_t, "Char index of the start of this node in the utterance graph") \
    visitor(end_pos, size_t, "Char index past end of this node in utterance graph")
#endif
