/**
 * @file hrglib/relation_list.hpp
 * @brief Definition of `HRGLIB_RELATION_LIST()` macro.
 */
#pragma once

/**
 * @brief Second-order macro used as a canonical source for emitting all dependent relation lists,
 *     including the implementation of `hrglib::relation_name` enum.
 * @todo This list can be autogenerated from relations.yaml or some other external database.
 */
#define HRGLIB_RELATION_LIST(visitor) \
    /*[[[cog
import cog
import yaml

with open(RELATIONS_YAML) as f:
    relations = yaml.load(f, Loader=yaml.SafeLoader)
    for rel in relations:
        def_node_type = f"node_<R::{rel['name']}>"
        def_rel_type = f"relation_<R::{rel['name']}>"
        cog.outl(f"visitor({rel['name']}, {rel.get('node_type', def_node_type)}, " +
                 f"{rel.get('relation_type', def_rel_type)}, {rel.get('parent', 'INVALID')}, " +
                 f"{rel.get('child', 'INVALID')}, \"{rel.get('description', '')}\") \\")
    ]]]*/
    //[[[end]]]

    // visitor(Phrase) \
    // visitor(Token) \
    // visitor(Word) \
    // visitor(Syllable) \
    // visitor(Segment) \
    // visitor(SylStructure) \
    // visitor(Intonation) \
    // visitor(Unit)
