/**
 * @file hrglib/relation_list.hpp
 * @brief Definition of `HRGLIB_RELATION_LIST()` macro.
 */
#pragma once

/**
 * @brief Second-order macro used as a canonical source for emitting all dependent relation lists,
 *     including the implementation of `hrglib::relation_name` enum.
 * @todo This list can be autogenerated from relations.yaml or some other external database.
 */
#define HRGLIB_RELATION_LIST(visitor) \
    visitor(Phrase) \
    visitor(Token) \
    visitor(Word) \
    visitor(Syllable) \
    visitor(Segment) \
    visitor(SylStructure) \
    visitor(Intonation) \
    visitor(Unit)
