if(_ASANRulesOverrideModuleIncluded)
    return()
else()
    set(_ASANRulesOverrideModuleIncluded TRUE)
endif()

# set(_ASAN_C_CXX_COMMON_FLAGS)
# set(_ASAN_DYNAMIC_LINKER_FLAGS)
# set(_ASAN_STATIC_LINKER_FLAGS)

# if(CMAKE_C_COMPILER_ID MATCHES "Clang")
#     set(_ASAN_C_CXX_COMMON_FLAGS "${_ASAN_C_CXX_COMMON_FLAGS} -fprofile-arcs -ftest-coverage -ggdb3 -O0")
#     set(_ASAN_DYNAMIC_LINKER_FLAGS "${_ASAN_DYNAMIC_LINKER_FLAGS} -coverage")
# elseif(CMAKE_C_COMPILER_ID MATCHES "GNU")
#     set(_ASAN_C_CXX_COMMON_FLAGS "${_ASAN_C_CXX_COMMON_FLAGS} -fprofile-arcs -ftest-coverage -ggdb3 -O0")
#     set(_ASAN_DYNAMIC_LINKER_FLAGS "${_ASAN_DYNAMIC_LINKER_FLAGS} -lgcov")
# endif()

# set(CMAKE_C_FLAGS_COVERAGE_INIT "${CMAKE_C_FLAGS_DEBUG_INIT} ${_ASAN_C_CXX_COMMON_FLAGS}")
# set(CMAKE_CXX_FLAGS_COVERAGE_INIT "${CMAKE_CXX_FLAGS_DEBUG_INIT} ${_ASAN_C_CXX_COMMON_FLAGS}")

# set(CMAKE_SHARED_LINKER_FLAGS_COVERAGE_INIT "${CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT} ${_ASAN_DYNAMIC_LINKER_FLAGS}")
# set(CMAKE_EXE_LINKER_FLAGS_COVERAGE_INIT "${CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT} ${_ASAN_DYNAMIC_LINKER_FLAGS}")
# set(CMAKE_MODULE_LINKER_FLAGS_COVERAGE_INIT "${CMAKE_MONULE_LINKER_FLAGS_DEBUG_INIT} ${_ASAN_DYNAMIC_LINKER_FLAGS}")
# set(CMAKE_STATIC_LINKER_FLAGS_COVERAGE_INIT "${CMAKE_STATIC_LINKER_FLAGS_DEBUG_INIT} ${_ASAN_STATIC_LINKER_FLAGS}")

# list(APPEND CMAKE_CONFIGURATION_TYPES Coverage)
