if(_CoverageRulesOverrideModuleIncluded)
    return()
else()
    set(_CoverageRulesOverrideModuleIncluded TRUE)
endif()

if(NOT Coverage_BASE_CONFIGURATION)
    set(Coverage_BASE_CONFIGURATION RelWithDebInfo)
endif()
string(TOUPPER "${Coverage_BASE_CONFIGURATION}" Coverage_BASE_CONFIGURATION)

set(_Coverage_C_CXX_COMMON_FLAGS)
set(_Coverage_DYNAMIC_LINKER_FLAGS)
set(_Coverage_STATIC_LINKER_FLAGS)

if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    #  -fprofile-abs-path
    set(_Coverage_C_CXX_COMMON_FLAGS "${_Coverage_C_CXX_COMMON_FLAGS} -fprofile-arcs -ftest-coverage -ggdb3")
    set(_Coverage_DYNAMIC_LINKER_FLAGS "${_Coverage_DYNAMIC_LINKER_FLAGS} -fprofile-arcs")
else() 
    message(WARNING "Coverage is not available with compiler ${CMAKE_C_COMPILER_ID}")
endif()

set(CMAKE_CXX_FLAGS_COVERAGE_INIT "${CMAKE_CXX_FLAGS_${Coverage_BASE_CONFIGURATION}_INIT} ${_Coverage_C_CXX_COMMON_FLAGS}")
set(CMAKE_C_FLAGS_COVERAGE_INIT "${CMAKE_C_FLAGS_${Coverage_BASE_CONFIGURATION}_INIT} ${_Coverage_C_CXX_COMMON_FLAGS}")

set(CMAKE_SHARED_LINKER_FLAGS_COVERAGE_INIT "${CMAKE_SHARED_LINKER_FLAGS_${Coverage_BASE_CONFIGURATION}_INIT} ${_Coverage_DYNAMIC_LINKER_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_COVERAGE_INIT "${CMAKE_EXE_LINKER_FLAGS_${Coverage_BASE_CONFIGURATION}_INIT} ${_Coverage_DYNAMIC_LINKER_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_COVERAGE_INIT "${CMAKE_MONULE_LINKER_FLAGS_${Coverage_BASE_CONFIGURATION}_INIT} ${_Coverage_DYNAMIC_LINKER_FLAGS}")
set(CMAKE_STATIC_LINKER_FLAGS_COVERAGE_INIT "${CMAKE_STATIC_LINKER_FLAGS_${Coverage_BASE_CONFIGURATION}_INIT} ${_Coverage_STATIC_LINKER_FLAGS}")

get_property(_Coverage_GENERATOR_MULTI_CONFIG GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)

if(_Coverage_GENERATOR_MULTI_CONFIG)
    if(NOT "Coverage" IN_LIST CMAKE_CONFIGURATION_TYPES)
        list(APPEND CMAKE_CONFIGURATION_TYPES Coverage)
    endif()
endif()
