if(_CoverageModuleIncluded)
    return()
else()
    set(_CoverageModuleIncluded TRUE)
endif()

if(NOT CMAKE_C_COMPILER_ID)
    enable_language(C)
endif()

set(CMAKE_C_CXX_COMMON_FLAGS_COVERAGE "-fprofile-arcs -ftest-coverage -ggdb3 -O0")
set(CMAKE_C_FLAGS_COVERAGE_INIT "${CMAKE_C_CXX_COMMON_FLAGS_COVERAGE}")
set(CMAKE_CXX_FLAGS_COVERAGE_INIT "${CMAKE_C_CXX_COMMON_FLAGS_COVERAGE}")

set(CMAKE_LINKER_COMMON_FLAGS_COVERAGE)

if(CMAKE_C_COMPILER_ID MATCHES "(Apple)?[Cc]lang")
    set(CMAKE_LINKER_COMMON_FLAGS_COVERAGE "${CMAKE_LINKER_COMMON_FLAGS_COVERAGE} -coverage")
elseif(CMAKE_C_COMPILER_ID MATCHES "GNU")
    link_libraries(gcov)
endif()

set(CMAKE_SHARED_LINKER_FLAGS_COVERAGE_INIT "${CMAKE_LINKER_COMMON_FLAGS_COVERAGE}")
set(CMAKE_EXE_LINKER_FLAGS_COVERAGE_INIT "${CMAKE_LINKER_COMMON_FLAGS_COVERAGE}")
set(CMAKE_MODULE_LINKER_FLAGS_COVERAGE_INIT "${CMAKE_LINKER_COMMON_FLAGS_COVERAGE}")
set(CMAKE_STATIC_LINKER_FLAGS_COVERAGE_INIT "${CMAKE_LINKER_COMMON_FLAGS_COVERAGE}")

list(APPEND CMAKE_CONFIGURATION_TYPES Coverage)
